owner: mrGhostage
repo: guessr-place-status

sites:
  - name: Guessr Front
    url: https://guessr.place/Healthz

  - name: Guessr API (prod)
    url: https://api.guessr.place/admin/healthz

assignees:
  - mrGhostage

status-website:
  baseUrl: /guessr-place-status
  name: Guessr.Place Status
  theme: night
